services:
  kasm-homepilot:
    image: ghcr.io/mtclab/kasm-homepilot-workspace:latest
    container_name: kasm-homepilot
    ports:
      - "6902:6901"
    shm_size: "256m"
    environment:
      - VNC_PW=password
